if(NOT DEFINED IR_FILE)
    message(FATAL_ERROR "IR_FILE is required")
endif()

file(READ "${IR_FILE}" ir)

foreach(type_name IN ITEMS ResourceBase ResourceDerived)
    if(NOT ir MATCHES "@absolute[.]vtable[.]${type_name} = private constant \\[[^]]+\\] \\[ptr @${type_name}[.]__destroy")
        message(FATAL_ERROR "${type_name} vtable does not reserve destructor slot zero")
    endif()
    if(NOT ir MATCHES "define internal void @${type_name}[.]__destroy\\(ptr %this\\)")
        message(FATAL_ERROR "missing generated destructor for ${type_name}")
    endif()
endforeach()

if(NOT ir MATCHES "define internal void @ResourceBuffer[.]__destroy\\(ptr %this\\)")
    message(FATAL_ERROR "missing generated struct destructor")
endif()
if(NOT ir MATCHES "call void @absolute_managed_destroy")
    message(FATAL_ERROR "managed resource field cleanup was not emitted")
endif()
if(NOT ir MATCHES "call void @free\\(ptr %field[.]cleanup[.]array[.]owner")
    message(FATAL_ERROR "array resource field cleanup was not emitted")
endif()
if(NOT ir MATCHES "aggregate[.]destroy[.]slot")
    message(FATAL_ERROR "polymorphic delete does not dispatch through destructor slot zero")
endif()
