if(NOT DEFINED IR_FILE)
    message(FATAL_ERROR "IR_FILE is required")
endif()

file(READ "${IR_FILE}" ir)
if(NOT ir MATCHES "define void @absolute[.]shader[.]Vertex")
    message(FATAL_ERROR "opaque shader function is missing from linked LLVM IR")
endif()
if(NOT ir MATCHES "@absolute[.]shader[.]Vertex[.]input_count = constant i32 2")
    message(FATAL_ERROR "shader input metadata is missing")
endif()
if(NOT ir MATCHES "@absolute[.]shader[.]Vertex[.]output_count = constant i32 1")
    message(FATAL_ERROR "shader output metadata is missing")
endif()
if(NOT ir MATCHES "@absolute[.]shader[.]Vertex[.]metadata_count = constant i32 1")
    message(FATAL_ERROR "shader attribute metadata was not passed to LLVM emission")
endif()
