if(NOT DEFINED IR_FILE OR NOT EXISTS "${IR_FILE}")
    message(FATAL_ERROR "Value-reference LLVM IR file is missing: ${IR_FILE}")
endif()

file(READ "${IR_FILE}" IR)

function(require_signature FUNCTION_NAME OUTPUT_VARIABLE)
    string(REGEX MATCH "define[^\r\n]*@${FUNCTION_NAME}[^\r\n]*" signature "${IR}")
    if(NOT signature)
        message(FATAL_ERROR "LLVM IR definition for ${FUNCTION_NAME} was not found")
    endif()
    set(${OUTPUT_VARIABLE} "${signature}" PARENT_SCOPE)
endfunction()

function(require_parameter_attribute SIGNATURE ATTRIBUTE DESCRIPTION)
    string(FIND "${SIGNATURE}" "${ATTRIBUTE}" attribute_position)
    if(attribute_position EQUAL -1)
        message(FATAL_ERROR "${DESCRIPTION} is missing '${ATTRIBUTE}': ${SIGNATURE}")
    endif()
endfunction()

function(require_no_capture SIGNATURE DESCRIPTION)
    # LLVM 21 may canonicalize nocapture as the generalized captures(none)
    # spelling. Accept both while still requiring the same semantic contract.
    string(FIND "${SIGNATURE}" "nocapture" nocapture_position)
    string(FIND "${SIGNATURE}" "captures(none)" captures_none_position)
    if(nocapture_position EQUAL -1 AND captures_none_position EQUAL -1)
        message(FATAL_ERROR "${DESCRIPTION} is missing nocapture/captures(none): ${SIGNATURE}")
    endif()
endfunction()

require_signature("inspect" inspect_signature)
require_parameter_attribute("${inspect_signature}" "nonnull" "const T& parameter")
require_no_capture("${inspect_signature}" "const T& parameter")
require_parameter_attribute("${inspect_signature}" "readonly" "const T& parameter")

require_signature("add" add_signature)
require_parameter_attribute("${add_signature}" "nonnull" "mutable T& parameter")
require_no_capture("${add_signature}" "mutable T& parameter")
string(FIND "${add_signature}" "readonly" mutable_readonly_position)
if(NOT mutable_readonly_position EQUAL -1)
    message(FATAL_ERROR "mutable T& parameter was incorrectly marked readonly: ${add_signature}")
endif()

string(FIND "${IR}" "const.ref.temporary" temporary_position)
if(temporary_position EQUAL -1)
    message(FATAL_ERROR "const T& temporary lifetime storage was not emitted")
endif()
string(FIND "${IR}" "value.argument.copy" copy_position)
if(NOT copy_position EQUAL -1)
    message(FATAL_ERROR "value-reference call unexpectedly materializes a by-value copy")
endif()
