if(NOT DEFINED IR_FILE)
    message(FATAL_ERROR "IR_FILE is required")
endif()

file(READ "${IR_FILE}" ir)
string(REGEX MATCHALL "call ptr @absolute_managed_require" require_calls "${ir}")
list(LENGTH require_calls require_count)
if(NOT require_count EQUAL 1)
    message(FATAL_ERROR "expected one managed_require at allocation, found ${require_count}")
endif()
if(ir MATCHES "[.]owner = alloca i1" OR ir MATCHES "absolute_managed_destroy_if")
    message(FATAL_ERROR "runtime owner flag remains in generated IR")
endif()
if(NOT ir MATCHES "cached[.]pointee")
    message(FATAL_ERROR "managed owner pointee cache is missing")
endif()
