#!/usr/bin/env python3
"""Generate valid typed programs and run them under AddressSanitizer.

The corpora that exist generate one shape each -- integer mixing, floating
arithmetic, integer edges, ownership operations -- and none of them is compiled
with a sanitizer. What the backend actually emits for the rest of the language
is never fuzzed: arrays with computed indices, classes with fields and methods,
managed owners created and deleted while a loop runs over them, nested control
flow that decides which of those happens.

Every program here is valid by construction and self-checking by construction:
it accumulates a checksum from what it did and prints it. The oracle is
agreement rather than a model -- the same program at -O0 and at -O3 must print
the same number -- plus the sanitizer and the runtime's own leak check, which
answer a different question: not "is the number right" but "did the program
touch memory it should not have, or leave some behind".

A model in Python would be a second implementation of the semantics, able to be
wrong on its own; the two oracles here cannot be wrong, only silent.
"""

from __future__ import annotations

import argparse
import os
import random
import subprocess
import sys
from pathlib import Path


def generate(seed: int) -> str:
    """One valid program: a class with an array field, a managed owner, loops."""
    rng = random.Random(seed)
    size = rng.randint(4, 32)
    rounds = rng.randint(2, 12)
    step = rng.randint(1, 7)
    bias = rng.randint(1, 97)
    threshold = rng.randint(1, max(2, size - 1))
    depth = rng.randint(1, 3)

    # Every index is computed and then brought back into range by a remainder,
    # so the program is valid however the constants fall.
    body = f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}.
class Cell {{
    public int32 value;
    public Cell(int32 initial) {{ value = initial; }}
    public int32 mixed(int32 salt) {{ return (value * 3 + salt) % 100003; }}
}}

class Board {{
    public int32[] cells;
    public int32 count;
    public Cell* marker;

    public Board(int32 size) {{
        cells = new int32[size];
        count = size;
        marker = new Cell({bias});
        int32 index = 0;
        while (index < count) {{
            cells[index] = (index * {step} + {bias}) % 1009;
            index += 1;
        }}
    }}

    public int64 sweep(int32 round) {{
        int64 total = 0;
        int32 index = 0;
        while (index < count) {{
            int32 probe = (index * {step} + round) % count;
            int32 current = cells[probe];
            if (current % 2 == 0) {{
                cells[probe] = current + round;
                total += current;
            }}
            else {{
                cells[probe] = current - 1;
                total -= 1;
            }}
            if (probe < {threshold}) {{
                total += marker.mixed(current % 97);
            }}
            index += 1;
        }}
        return total;
    }}

    // The managed field is released by the object's own destructor, in reverse
    // declaration order; a hook that deleted it would be deleting a subscriber.
    public void destroy() {{ count = 0; }}
}}

int64 nested(int32 value, int32 level) {{
    if (level <= 0) {{ return value % 5003; }}
    int64 folded = 0;
    int32 index = 0;
    while (index < 4) {{
        folded += nested(value + index * {step}, level - 1);
        index += 1;
    }}
    return folded % 100019;
}}

int32 main() {{
    int64 checksum = 0;
    Board* board = new Board({size});
    int32 round = 0;
    while (round < {rounds}) {{
        checksum += board.sweep(round);
        checksum = checksum % 1000003;
        round += 1;
    }}
    delete board;

    // A local array, an owner that outlives a loop, and one that does not.
    int32[] scratch = new int32[{size}];
    int32 index = 0;
    while (index < {size}) {{
        Cell* cell = new Cell(index * {step} + {bias});
        scratch[index] = cell.mixed(index % 89);
        checksum += scratch[index];
        delete cell;
        index += 1;
    }}
    checksum += nested({bias}, {depth});
    // Printed as a number rather than through `format`, so the leak check
    // stays meaningful: a string has no lifetime yet (docs/known-defects.md)
    // and every `format` call would leak its buffer into the report.
    println(checksum % 1000003);
    return 0;
}}
"""
    return body


def run(command: list[str], timeout: int, environment: dict | None = None):
    return subprocess.run(command, capture_output=True, text=True,
                          encoding="utf-8", errors="replace", timeout=timeout,
                          check=False, env=environment)


SANITIZER_MARKERS = ("AddressSanitizer", "LeakSanitizer", "runtime error:",
                     "memory leak detected", "managed pointer(s) leaked")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path, required=True)
    parser.add_argument("--cases", type=int, default=12)
    parser.add_argument("--seed", type=int, default=20260818)
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--configuration", default="")
    # Where the platform's sanitizer has no leak checker -- Windows, Termux --
    # the run still checks the other two things it can: that the program
    # touched no memory it should not have, and that -O0 and -O3 agree.
    parser.add_argument("--detect-leaks", default="1",
                        choices=("0", "1", "ON", "OFF"))
    args = parser.parse_args()

    work = args.work_dir.resolve()
    work.mkdir(parents=True, exist_ok=True)
    compiler = args.compiler.resolve()
    environment = os.environ.copy()
    leaks = "1" if args.detect_leaks in ("1", "ON") else "0"
    environment["ASAN_OPTIONS"] = f"detect_leaks={leaks}:abort_on_error=0"

    failures = 0
    for index in range(args.cases):
        seed = args.seed + index
        source = work / f"case-{seed}.abs"
        source.write_text(generate(seed), encoding="utf-8")

        answers = {}
        for level, sanitize in (("O0", True), ("O3", False)):
            binary = work / f"case-{seed}-{level}"
            command = [str(compiler), str(source), f"-{level}", "--build-exe",
                       "-o", str(binary)]
            if sanitize:
                command.insert(2, "--sanitize=address")
            build = run(command, args.timeout)
            if build.returncode != 0:
                print(f"BUILD FAILED seed={seed} level={level}")
                print(build.stdout[-800:] + build.stderr[-800:])
                failures += 1
                break
            result = run([str(binary)], args.timeout, environment)
            output = result.stdout + result.stderr
            if result.returncode != 0 or any(
                    marker in output for marker in SANITIZER_MARKERS):
                print(f"RUN FAILED seed={seed} level={level} "
                      f"exit={result.returncode}")
                print(output[-1200:])
                print(f"    reproduce: {source}")
                failures += 1
                break
            answers[level] = result.stdout.strip()
        else:
            if len(set(answers.values())) > 1:
                print(f"DISAGREEMENT seed={seed}: {answers}")
                print(f"    reproduce: {source}")
                failures += 1

    print(f"codegen-fuzz={'ok' if failures == 0 else 'failed'} "
          f"cases={args.cases} seed={args.seed} failures={failures} "
          f"configuration={args.configuration}")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
