#!/usr/bin/env python3
"""Generate valid typed programs and run them under AddressSanitizer.

The corpora that exist generate one shape each -- integer mixing, floating
arithmetic, integer edges, ownership operations -- and none of them is compiled
with a sanitizer. What the backend actually emits for the rest of the language
is never fuzzed: arrays with computed indices, classes with fields and methods,
managed owners created and deleted while a loop runs over them, nested control
flow that decides which of those happens.

Every program here is valid by construction and self-checking by construction:
it accumulates a checksum from what it did and prints it. The oracle is
agreement rather than a model -- the same program at -O0 and at -O3 must print
the same number -- plus the sanitizer and the runtime's own leak check, which
answer a different question: not "is the number right" but "did the program
touch memory it should not have, or leave some behind".

A model in Python would be a second implementation of the semantics, able to be
wrong on its own; the two oracles here cannot be wrong, only silent.
"""

from __future__ import annotations

import argparse
import os
import random
import subprocess
import sys
from pathlib import Path


def generate_board(seed: int) -> str:
    """A class with an array field, a managed owner, loops and recursion."""
    rng = random.Random(seed)
    size = rng.randint(4, 32)
    rounds = rng.randint(2, 12)
    step = rng.randint(1, 7)
    bias = rng.randint(1, 97)
    threshold = rng.randint(1, max(2, size - 1))
    depth = rng.randint(1, 3)

    # Every index is computed and then brought back into range by a remainder,
    # so the program is valid however the constants fall.
    body = f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}.
class Cell {{
    public int32 value;
    public Cell(int32 initial) {{ value = initial; }}
    public int32 mixed(int32 salt) {{ return (value * 3 + salt) % 100003; }}
}}

class Board {{
    public int32[] cells;
    public int32 count;
    public Cell* marker;

    public Board(int32 size) {{
        cells = new int32[size];
        count = size;
        marker = new Cell({bias});
        int32 index = 0;
        while (index < count) {{
            cells[index] = (index * {step} + {bias}) % 1009;
            index += 1;
        }}
    }}

    public int64 sweep(int32 round) {{
        int64 total = 0;
        int32 index = 0;
        while (index < count) {{
            int32 probe = (index * {step} + round) % count;
            int32 current = cells[probe];
            if (current % 2 == 0) {{
                cells[probe] = current + round;
                total += current;
            }}
            else {{
                cells[probe] = current - 1;
                total -= 1;
            }}
            if (probe < {threshold}) {{
                total += marker.mixed(current % 97);
            }}
            index += 1;
        }}
        return total;
    }}

    // The managed field is released by the object's own destructor, in reverse
    // declaration order; a hook that deleted it would be deleting a subscriber.
    public void destroy() {{ count = 0; }}
}}

int64 nested(int32 value, int32 level) {{
    if (level <= 0) {{ return value % 5003; }}
    int64 folded = 0;
    int32 index = 0;
    while (index < 4) {{
        folded += nested(value + index * {step}, level - 1);
        index += 1;
    }}
    return folded % 100019;
}}

int32 main() {{
    int64 checksum = 0;
    Board* board = new Board({size});
    int32 round = 0;
    while (round < {rounds}) {{
        checksum += board.sweep(round);
        checksum = checksum % 1000003;
        round += 1;
    }}
    delete board;

    // A local array, an owner that outlives a loop, and one that does not.
    int32[] scratch = new int32[{size}];
    int32 index = 0;
    while (index < {size}) {{
        Cell* cell = new Cell(index * {step} + {bias});
        scratch[index] = cell.mixed(index % 89);
        checksum += scratch[index];
        delete cell;
        index += 1;
    }}
    checksum += nested({bias}, {depth});
    // Printed as a number rather than through `format`, so the leak check
    // stays meaningful: a string has no lifetime yet (docs/known-defects.md)
    // and every `format` call would leak its buffer into the report.
    println(checksum % 1000003);
    return 0;
}}
"""
    return body


def generate_dispatch(seed: int) -> str:
    """Virtual dispatch: an interface, several implementations, a loop over
    an array of owners that calls through the vtable."""
    rng = random.Random(seed)
    count = rng.randint(3, 24)
    rounds = rng.randint(2, 8)
    weights = [rng.randint(1, 40) for _ in range(3)]
    offset = rng.randint(1, 61)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape dispatch.
interface IScore {{
    int64 score(int64 input);

    // A default body calling the rest of the contract has to reach the
    // concrete implementation through the vtable, not the declaration.
    int64 doubled(int64 input) {{ return score(input) * 2; }}
}}

class Flat : IScore {{
    public int64 bias;
    public Flat(int64 value) {{ bias = value; }}
    public virtual int64 score(int64 input) {{
        return (input + bias) % 100003;
    }}
}}

class Scaled : Flat {{
    public int64 factor;
    public Scaled(int64 value, int64 scale) {{
        base(value);
        factor = scale;
    }}
    // Overrides an override: the vtable slot the interface names has to reach
    // this body, not the one the base class installed.
    public virtual int64 score(int64 input) {{
        return ((input + bias) * factor) % 100003;
    }}
}}

class Folded : IScore {{
    public int64[] history;
    public int64 cursor;
    public Folded(int32 size) {{
        history = new int64[size];
        cursor = 0;
    }}
    public virtual int64 score(int64 input) {{
        history[cursor % history.length] = input;
        cursor += 1;
        int64 total = 0;
        int32 index = 0;
        while (index < history.length) {{
            total += history[index];
            index += 1;
        }}
        return total % 100003;
    }}
}}

int64 through(IScore* subject, int64 input) {{
    // Reached as an interface, so every call is a vtable call.
    return subject.doubled(input) + subject.score(input + 1);
}}

int32 main() {{
    int64 checksum = 0;
    int32 index = 0;
    while (index < {count}) {{
        IScore* subject = null;
        if (index % 3 == 0) {{ subject = new Flat(index * {weights[0]} + {offset}); }}
        else if (index % 3 == 1) {{ subject = new Scaled(index + {weights[1]}, {weights[2]}); }}
        else {{ subject = new Folded(index % 5 + 1); }}

        int32 round = 0;
        while (round < {rounds}) {{
            checksum += through(subject, index * round + {offset});
            checksum = checksum % 1000003;
            round += 1;
        }}
        delete subject;
        index += 1;
    }}
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_unwind(seed: int) -> str:
    """Exceptions: owners in flight when a throw leaves a frame, defer and
    finally on the way out, a catch that folds the failure into the answer."""
    rng = random.Random(seed)
    depth = rng.randint(1, 4)
    trips = rng.randint(2, 16)
    modulus = rng.randint(2, 7)
    bias = rng.randint(1, 89)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape unwind.
class Failure : Error {{
    public int64 code;
    public Failure(string text, int64 value) {{
        base(text);
        code = value;
    }}
}}

class Holder {{
    public int64[] cells;
    public int64 total;
    public Holder(int32 size, int64 seed) {{
        cells = new int64[size];
        int32 index = 0;
        while (index < size) {{
            cells[index] = (index * seed + {bias}) % 1009;
            index += 1;
        }}
        total = 0;
    }}
    public int64 fold() {{
        int32 index = 0;
        while (index < cells.length) {{
            total += cells[index];
            index += 1;
        }}
        return total % 100003;
    }}
}}

// The owner is alive when the throw happens, so leaving through the exception
// path has to release exactly what leaving through the return path releases.
int64 descend(int64 value, int32 level, raw int64* visits) {{
    Holder* holder = new Holder(level + 2, value);
    defer {{ *visits += 1; }}
    int64 folded = holder.fold();
    if (level <= 0) {{
        if (value % {modulus} == 0) {{
            delete holder;
            throw new Failure("bottom", folded);
        }}
        delete holder;
        return folded;
    }}
    try {{
        int64 deeper = descend(value + level, level - 1, visits);
        delete holder;
        return (folded + deeper) % 100003;
    }}
    catch (Failure* failure) {{
        int64 recovered = (folded + failure.code) % 100003;
        delete holder;
        return recovered;
    }}
}}

int32 main() {{
    int64 checksum = 0;
    int64 visits = 0;
    raw int64* visitCount = &visits;
    int32 trip = 0;
    while (trip < {trips}) {{
        try {{
            checksum += descend(trip + {bias}, {depth}, visitCount);
        }}
        catch (Failure* failure) {{
            checksum += failure.code + 1;
        }}
        checksum = checksum % 1000003;
        trip += 1;
    }}
    println((checksum + visits) % 1000003);
    return 0;
}}
"""


def generate_closures(seed: int) -> str:
    """Lambdas: captured locals, a closure stored and called after the value it
    captured changed, closures handed to and returned from functions."""
    rng = random.Random(seed)
    rounds = rng.randint(4, 40)
    step = rng.randint(1, 9)
    bias = rng.randint(1, 73)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape closures.
func<int64, int64> adder(int64 amount) {{
    // Escapes the frame that made it, so the capture outlives its source.
    return fn(int64 value) => (value + amount) % 100003;
}}

int64 applyTwice(func<int64, int64> operation, int64 value) {{
    return operation(operation(value));
}}

int64 accumulate(func<int64, int64> operation, int32 count, int64 start) {{
    int64 total = start;
    int32 index = 0;
    while (index < count) {{
        total = (total + operation(index)) % 100003;
        index += 1;
    }}
    return total;
}}

int32 main() {{
    int64 checksum = 0;
    int64 captured = {bias};
    func<int64, int64> scale = fn(int64 value) => (value * {step} + captured) % 100003;
    // A copy keeps the environment it was made with; reassignment releases the
    // old owner rather than the copy's.
    func<int64, int64> copied = scale;
    captured = {bias} * 2;
    scale = fn(int64 value) => (value + {step}) % 100003;

    checksum += applyTwice(copied, {bias});
    checksum += applyTwice(scale, {bias});
    checksum = checksum % 1000003;

    func<int64, int64> escaped = adder({bias});
    checksum += accumulate(escaped, {rounds}, checksum);
    checksum = checksum % 1000003;

    int32 index = 0;
    while (index < {rounds}) {{
        // A fresh closure on every iteration: the scope releases each one as
        // it closes, rather than the last one only.
        int64 local = index * {step};
        func<int64, int64> perRound = fn(int64 value) => (value + local) % 100003;
        checksum += perRound(index);
        checksum = checksum % 1000003;
        index += 1;
    }}
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_generics(seed: int) -> str:
    """Generics: one function and one class specialized at several widths, so
    the same source produces several bodies that must each be right."""
    rng = random.Random(seed)
    size = rng.randint(3, 20)
    step = rng.randint(1, 11)
    bias = rng.randint(1, 53)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape generics.
T pick<T>(T[] values, int32 index) {{
    return values[index % values.length];
}}

// Values of an unconstrained type parameter are moved around, not computed
// with: the language has no numeric constraint to say `T + T` is allowed.
T[] pair<T>(T left, T right) {{
    T[] made = new T[2];
    made[0] = left;
    made[1] = right;
    return made;
}}

class Box<T> {{
    public T[] items;
    public int32 used;

    public Box(int32 size) {{
        items = new T[size];
        used = 0;
    }}

    public void put(T value) {{
        items[used % items.length] = value;
        used += 1;
    }}

    public T at(int32 index) {{
        return items[index % items.length];
    }}
}}

int32 main() {{
    int64 checksum = 0;

    int32[] narrow = new int32[{size}];
    int64[] wide = new int64[{size}];
    int32 index = 0;
    while (index < {size}) {{
        narrow[index] = index * {step} + {bias};
        wide[index] = index * {step} * 1000 + {bias};
        index += 1;
    }}

    index = 0;
    while (index < {size} * 2) {{
        checksum += pick(narrow, index);
        checksum += pick(wide, index) % 100003;
        checksum = checksum % 1000003;
        index += 1;
    }}

    int32[] narrowPair = pair<int32>({bias}, {step});
    int64[] widePair = pair<int64>({bias} * 1000, {step});
    checksum += narrowPair[0] + narrowPair[1];
    checksum += (widePair[0] + widePair[1]) % 100003;
    checksum = checksum % 1000003;

    Box<int32>* narrowBox = new Box<int32>({size});
    Box<int64>* wideBox = new Box<int64>({size});
    index = 0;
    while (index < {size} * 2) {{
        narrowBox.put(index * {step});
        wideBox.put(index * {step} * 100);
        index += 1;
    }}
    index = 0;
    while (index < {size}) {{
        checksum += narrowBox.at(index);
        checksum += wideBox.at(index) % 100003;
        checksum = checksum % 1000003;
        index += 1;
    }}
    delete narrowBox;
    delete wideBox;

    println(checksum % 1000003);
    return 0;
}}
"""


def generate_values(seed: int) -> str:
    """Structs by value: copied into and out of calls, mutated through a value
    reference, stored in an array, read back through a const reference."""
    rng = random.Random(seed)
    size = rng.randint(3, 20)
    rounds = rng.randint(2, 10)
    step = rng.randint(1, 13)
    bias = rng.randint(1, 67)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape values.
struct Sample {{
    int64 first;
    int64 second;
    int64 third;
}}

Sample make(int64 base) {{
    Sample value;
    value.first = base % 100003;
    value.second = (base * {step}) % 100003;
    value.third = (base + {bias}) % 100003;
    return value;
}}

// A copy: what the caller passed cannot change.
int64 total(Sample value) {{
    value.first += 1;
    return (value.first + value.second + value.third) % 100003;
}}

// The same value, not a copy of it.
int64 totalByReference(const Sample& value) {{
    return (value.first + value.second + value.third) % 100003;
}}

void bump(Sample& value, int64 amount) {{
    value.first = (value.first + amount) % 100003;
    value.third = (value.third + amount) % 100003;
}}

int32 main() {{
    int64 checksum = 0;

    Sample single = make({bias});
    int64 beforeCopy = single.first;
    checksum += total(single);
    // The callee incremented its own copy, so this must not have moved.
    if (single.first != beforeCopy) {{ println(-1); return 1; }}
    checksum += totalByReference(single);
    bump(single, {step});
    checksum += single.first + single.third;
    checksum = checksum % 1000003;

    Sample[] samples = new Sample[{size}];
    int32 index = 0;
    while (index < {size}) {{
        samples[index] = make(index * {step} + {bias});
        index += 1;
    }}

    int32 round = 0;
    while (round < {rounds}) {{
        index = 0;
        while (index < {size}) {{
            // Reading an element copies it; writing one back stores a copy.
            Sample element = samples[index];
            bump(element, round + index);
            samples[index] = element;
            checksum += totalByReference(samples[index]);
            checksum = checksum % 1000003;
            index += 1;
        }}
        round += 1;
    }}

    println(checksum % 1000003);
    return 0;
}}
"""


def generate_control(seed: int) -> str:
    """Control flow: switch and match over an enum, nested loops with break and
    continue, defer running in reverse on every way out of a scope."""
    rng = random.Random(seed)
    rounds = rng.randint(4, 40)
    inner = rng.randint(2, 9)
    step = rng.randint(1, 11)
    bias = rng.randint(1, 47)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape control.
enum Phase {{
    Start = {bias},
    Middle = {bias * 2},
    End = {bias * 3}
}}

int64 phaseScore(Phase phase) {{
    match (phase) {{
    case Phase.Start:
        return {step};
    case Phase.Middle:
        return {step} * 2;
    case Phase.End:
        return {step} * 3;
    }}
}}

int64 bucket(int64 value) {{
    switch (value % 5) {{
    case 0:
        return 1;
    case 1:
        return 3;
    case 4:
        return 7;
    default:
        return 11;
    }}
}}

// Deferred statements run in reverse order on every way out, including the
// early one, so the count they leave behind says which paths were taken.
int64 walk(int32 limit, raw int64* trail) {{
    defer {{ *trail += 1; }}
    int64 total = 0;
    int32 outer = 0;
    while (outer < limit) {{
        defer {{ *trail += 2; }}
        int32 index = 0;
        while (index < {inner}) {{
            if ((index + outer) % 3 == 0) {{ index += 1; continue; }}
            if (index * outer > {rounds} * {inner}) {{ break; }}
            total += bucket(index * outer + {bias});
            index += 1;
        }}
        if (total > 100003) {{ return total % 100003; }}
        outer += 1;
    }}
    return total % 100003;
}}

int32 main() {{
    int64 checksum = 0;
    int64 trail = 0;
    raw int64* trailAddress = &trail;

    checksum += phaseScore(Phase.Start);
    checksum += phaseScore(Phase.Middle);
    checksum += phaseScore(Phase.End);
    checksum += Phase.Middle as int64;
    if ((Phase.End as int64) != {bias * 3}) {{ println(-1); return 1; }}

    int32 round = 0;
    while (round < {rounds}) {{
        checksum += walk(round % 7 + 1, trailAddress);
        checksum = checksum % 1000003;
        round += 1;
    }}
    println((checksum + trail) % 1000003);
    return 0;
}}
"""


def generate_accessors(seed: int) -> str:
    """Properties and indexers: auto-implemented and explicit, reached through
    an interface and through a concrete type, read and written in a loop."""
    rng = random.Random(seed)
    size = rng.randint(4, 24)
    rounds = rng.randint(2, 9)
    step = rng.randint(1, 11)
    bias = rng.randint(1, 59)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape accessors.
interface ICounted {{
    int64 Total {{
        get;
        set;
    }}

    // A default getter that calls the rest of the contract has to reach the
    // concrete accessor through the vtable.
    int64 Doubled {{
        get {{ return Total * 2; }}
    }}

    int64 this[int32 index] {{
        get;
        set;
    }}
}}

class Ledger : ICounted {{
    private int64[] cells;

    public Ledger(int32 size) {{
        cells = new int64[size];
        Total = 0;
    }}

    // Auto-implemented: the hidden storage is the same field the interface
    // slot has to find.
    public int64 Total {{
        get;
        set;
    }}

    public int64 this[int32 index] {{
        get {{ return cells[index % cells.length]; }}
        set {{
            cells[index % cells.length] = value;
            Total = (Total + value) % 100003;
        }}
    }}

    // An explicit property over the same storage, with a narrower setter.
    public int64 Folded {{
        get {{
            int64 total = 0;
            int32 index = 0;
            while (index < cells.length) {{
                total += cells[index];
                index += 1;
            }}
            return total % 100003;
        }}
        private set {{ cells[0] = value; }}
    }}
}}

int64 through(ICounted* subject, int32 index, int64 value) {{
    subject[index] = value;
    return subject[index] + subject.Doubled;
}}

int32 main() {{
    int64 checksum = 0;
    Ledger* ledger = new Ledger({size});
    ICounted* counted = ledger;

    int32 round = 0;
    while (round < {rounds}) {{
        int32 index = 0;
        while (index < {size}) {{
            checksum += through(counted, index, (index * {step} + {bias}) % 1009);
            checksum = checksum % 1000003;
            index += 1;
        }}
        checksum += ledger.Folded;
        checksum += ledger.Total;
        checksum = checksum % 1000003;
        round += 1;
    }}
    delete ledger;
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_weak(seed: int) -> str:
    """Weak references under churn: owners created and deleted in a loop while
    observers of the slots they used are still held."""
    rng = random.Random(seed)
    rounds = rng.randint(4, 40)
    step = rng.randint(1, 13)
    bias = rng.randint(1, 71)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape weak.
class Node {{
    public int64 value;
    public weak Node* peer;

    public Node(int64 initial) {{
        value = initial;
        peer = null;
    }}

    public void connect(Node* other) {{ peer = other; }}

    public int64 peerValue() {{
        // An expired observer reads as false, and reading through it would be
        // the defect this shape exists to find.
        if (!peer) {{ return 0; }}
        return peer.value;
    }}
}}

weak Node* observe(Node* node) {{ return node; }}

int32 main() {{
    int64 checksum = 0;
    int64 expired = 0;

    int32 round = 0;
    while (round < {rounds}) {{
        Node* first = new Node(round * {step} + {bias});
        Node* second = new Node(round + {bias});
        first.connect(second);
        second.connect(first);

        weak Node* watcher = observe(first);
        if (watcher) {{ checksum += watcher.value; }}
        checksum += first.peerValue() + second.peerValue();
        checksum = checksum % 1000003;

        delete second;
        // The slot second used is free now; the observer that named it must
        // not come back to life when the next allocation takes that slot.
        if (!first.peerValue()) {{ expired += 1; }}
        Node* replacement = new Node(round + 1);
        if (!first.peerValue()) {{ expired += 1; }}
        checksum += replacement.value;
        delete replacement;

        if (!watcher) {{ expired += 1; }}
        delete first;
        if (!watcher) {{ expired += 1; }}
        checksum = checksum % 1000003;
        round += 1;
    }}
    // Three of the four checks above hold on every round; the fourth holds
    // only after the owner is gone. The count says which ones ran.
    println((checksum + expired) % 1000003);
    return 0;
}}
"""


def generate_aggregates(seed: int) -> str:
    """Tuples, params arrays, and static members: three ways a call can carry
    more than it declares."""
    rng = random.Random(seed)
    rounds = rng.randint(3, 24)
    step = rng.randint(1, 9)
    bias = rng.randint(1, 43)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape aggregates.
class Tally {{
    public static int64 seen = 0;
    public const static int64 stride = {step};

    public static int64 record(int64 amount) {{
        seen = (seen + amount) % 100003;
        return seen;
    }}

    public static int64 advance() {{ return record(stride); }}
}}

tuple<int64,int64,int64> triple(int64 seed) {{
    return (seed, (seed * {step}) % 100003, (seed + {bias}) % 100003);
}}

int64 collapse(tuple<int64,int64,int64> value) {{
    return (value.item0 + value.item1 + value.item2) % 100003;
}}

int64 gather(int64 base, params int64[] parts) {{
    int64 total = base;
    int32 index = 0;
    while (index < parts.length) {{
        total = (total + parts[index]) % 100003;
        index += 1;
    }}
    return total;
}}

T firstOf<T>(params T[] values) {{ return values[0]; }}

int32 main() {{
    int64 checksum = 0;

    int32 round = 0;
    while (round < {rounds}) {{
        int64 base = round * {step} + {bias};
        checksum += collapse(triple(base));
        // A params call with a spread of counts, including none.
        checksum += gather(base);
        checksum += gather(base, base + 1);
        checksum += gather(base, base + 1, base + 2, base + 3);
        // And with an array passed directly, which is the same call written
        // the other way.
        int64[] parts = new int64[3];
        parts[0] = base;
        parts[1] = base + {step};
        parts[2] = base + {bias};
        checksum += gather(0, parts);
        checksum += firstOf<int64>(base, base + 1);
        checksum += Tally.record(base);
        checksum += Tally.advance();
        checksum = checksum % 1000003;
        round += 1;
    }}
    checksum += Tally.seen;
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_counted(seed: int, std: Path) -> str:
    """A value whose parts are counted, through every place a copy happens.

    A string is shared: two names for the same bytes is the ordinary case, and
    the count behind the pointer says how many there are. An aggregate holding
    one is copied by copying its bytes, which duplicates the pointer and not
    the count, so every place a copy happens has to say there is a second name
    and every place one ends has to give the count back.

    Three of those places were missing when this shape was written, and none of
    the shapes that already existed went near them: `aggregates` builds tuples
    of numbers, `text` builds strings with no aggregate around them, and
    `handles` owns objects rather than sharing anything. What was missing was
    assignment of an aggregate, a value made only in order to pass in, and the
    two arms of a conditional -- which need not agree about who is holding what
    they hand back.

    The checksum is built from code points, so it changes if a string is the
    wrong bytes as well as if it is gone; the sanitizer answers for the rest.
    """
    rng = random.Random(seed)
    rounds = rng.randint(3, 18)
    step = rng.randint(1, 7)
    bias = rng.randint(1, 29)
    width = rng.randint(1, 5)
    library = (std / "string.abs").as_posix()

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape counted.
import "{library}";

struct Entry {{
    public string name;
    public string value;
    public int64 weight;
}}

int64 fold(string text) {{
    int32 count = std.text.codePointCount(text);
    int64 total = count;
    int32 index = 0;
    while (index < count) {{
        total = (total * 31 + std.text.codePointAt(text, index)) % 1000003;
        index += 1;
    }}
    return total;
}}

string make(int64 n) {{
    string result = "";
    int64 index = 0;
    while (index < n % {width} + 1) {{
        if (index % 2 == 0) {{ result = std.text.concat(result, "ab"); }}
        else {{ result = std.text.concat(result, "c"); }}
        index += 1;
    }}
    return result;
}}

Entry entryOf(int64 n) {{
    Entry made;
    made.name = make(n);
    made.value = make(n + {step});
    made.weight = n % 1000003;
    return made;
}}

tuple<int64,string> labelled(int64 n) {{ return (n % 1000003, make(n + {bias})); }}

// The parameter borrows: it takes no count and gives none back, so what the
// caller made is the caller's to release.
int64 weigh(Entry entry) {{
    return (fold(entry.name) + fold(entry.value) + entry.weight) % 1000003;
}}

int64 weighPair(tuple<int64,string> pair) {{
    return (pair.item0 + fold(pair.item1)) % 1000003;
}}

// A field read out of a value nobody keeps, handed on to the caller.
string nameOf(int64 n) {{ return entryOf(n).name; }}

class Store {{
    private Entry held;
    private tuple<int64,string> tagged;

    public Store() {{ held = entryOf(0); tagged = labelled(0); }}

    // A field assigned from a parameter: the field gives back what it held and
    // counts what it takes.
    public void keep(Entry entry) {{ held = entry; }}
    public void tag(tuple<int64,string> pair) {{ tagged = pair; }}

    // The same call written as a property and as an indexer, which are the two
    // that build their own call rather than going through the argument path.
    public Entry entry {{
        get {{ return held; }}
        set {{ held = value; }}
    }}

    public Entry this[int32 index] {{
        get {{ return held; }}
        set {{ held = value; }}
    }}

    public int64 reading() {{
        return (weigh(held) + weighPair(tagged)) % 1000003;
    }}
}}

int32 main() {{
    int64 checksum = 0;
    Store* store = new Store();
    // Held to the end, so every borrow of it below has to leave it alone.
    Entry kept = entryOf({bias});
    string keptText = make({bias});
    tuple<int64,string> keptPair = labelled({bias});

    int32 round = 0;
    while (round < {rounds}) {{
        int64 n = round * {step} + {bias};
        bool left = round % 2 == 0;

        // A declaration from a call and from a name.
        Entry fresh = entryOf(n);
        Entry copied = fresh;
        checksum += weigh(fresh) + weigh(copied);

        // Assignment: from a name, from a call, and to itself.
        Entry target = entryOf(n + 1);
        target = copied;
        checksum += weigh(target);
        target = entryOf(n + 2);
        checksum += weigh(target);
        target = target;
        checksum += weigh(target);

        // A value made only in order to pass it in.
        checksum += weigh(entryOf(n + 3));
        checksum += weighPair(labelled(n));
        checksum += fold(nameOf(n));

        // A conditional, with the arms holding and borrowing in turn.
        string text = left ? make(n) : keptText;
        checksum += fold(text);
        string other = left ? keptText : make(n + 1);
        checksum += fold(other);
        Entry picked = left ? entryOf(n + 4) : kept;
        checksum += weigh(picked);
        Entry another = left ? kept : entryOf(n + 5);
        checksum += weigh(another);
        tuple<int64,string> pair = left ? labelled(n) : keptPair;
        checksum += weighPair(pair);

        // A store into a slot, and a literal of aggregates.
        Entry[] slots = new Entry[3];
        unsafeArraySet(slots, 0, fresh);
        unsafeArraySet(slots, 1, entryOf(n + 6));
        unsafeArraySet(slots, 2, kept);
        checksum += weigh(slots[0]) + weigh(slots[1]) + weigh(slots[2]);
        Entry[] literal = {{ entryOf(n + 7), copied }};
        checksum += weigh(literal[0]) + weigh(literal[1]);

        // The same two written as storage the frame provides, which frees
        // nothing and still holds what its elements hold.
        Entry framed[2] = {{ entryOf(n + 8), kept }};
        checksum += weigh(framed[0]) + weigh(framed[1]);
        string words[2] = {{ make(n + 2), keptText }};
        checksum += fold(words[0]) + fold(words[1]);

        // A field, assigned from a parameter that borrowed it.
        store.keep(fresh);
        store.tag(labelled(n + 1));
        checksum += store.reading();
        store.entry = entryOf(n + 10);
        checksum += weigh(store.entry);
        store[0] = entryOf(n + 11);
        checksum += weigh(store[0]);

        checksum = checksum % 1000003;
        round += 1;
    }}

    // The names that were borrowed all the way through still hold their bytes.
    checksum += fold(kept.name) + fold(kept.value) + fold(keptText);
    checksum += weighPair(keptPair);
    checksum += store.reading();
    delete store;
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_owned(seed: int) -> str:
    """A value that holds an owner, which travels with a role rather than
    being copied.

    The `counted` shape carries values whose parts are *shared*, and the rules
    it exercises say nothing about a struct holding a `Node*`: there is no such
    thing as a second name for a unique owner, so such a value is not copyable
    at all. What is left is the other half of the same question -- where it may
    be handed on, and who destroys what a name held before it took another --
    and two of the answers were wrong. Assignment overwrote such a value
    without destroying what it held, and a conditional could not produce one at
    all, because whether an expression may hand one on was decided by asking
    whether its symbol is a callable.

    Every leak here is one the runtime reports at exit by handle, and the
    checksum is arithmetic, so a destroy that ran twice shows up as a wrong
    answer rather than as nothing at all.
    """
    rng = random.Random(seed)
    rounds = rng.randint(3, 18)
    step = rng.randint(1, 7)
    bias = rng.randint(1, 29)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape owned.
class Node {{
    public int64 value;
    public Node(int64 initial) {{ value = initial; }}
}}

struct Owner {{ public Node* node; public int64 tag; }}
struct Watcher {{ public sub Node* node; public int64 tag; }}
struct Weakly {{ public weak Node* node; public int64 tag; }}

Owner makeOwner(int64 n) {{
    Owner made;
    made.node = new Node(n % 100003);
    made.tag = n % 100003;
    return move(made);
}}

int64 readOwner(Owner held) {{ return (held.node.value + held.tag) % 100003; }}
int64 readWatcher(Watcher held) {{ return (held.node.value + held.tag) % 100003; }}

class Keeper {{
    private Owner held;
    public Keeper(int64 n) {{ held = makeOwner(n); }}
    public void replace(int64 n) {{ held = makeOwner(n); }}
    public int64 reading() {{ return readOwner(held); }}
}}

int32 main() {{
    int64 checksum = 0;
    Keeper* keeper = new Keeper({bias});
    Owner target = makeOwner({bias});

    int32 round = 0;
    while (round < {rounds}) {{
        int64 n = round * {step} + {bias};
        bool left = round % 2 == 0;

        // Assignment: what the target held is destroyed, and nothing else is.
        target = makeOwner(n);
        checksum += readOwner(target);
        target = left ? makeOwner(n + 1) : makeOwner(n + 2);
        checksum += readOwner(target);

        // A conditional both of whose arms produce a value, and a declaration
        // from each of the two shapes that may hand one on.
        Owner picked = left ? makeOwner(n + 3) : makeOwner(n + 4);
        checksum += readOwner(picked);
        Owner direct = makeOwner(n + 5);
        checksum += readOwner(direct);
        Owner moved = move(direct);
        checksum += readOwner(moved);

        // Borrowed by a parameter, taken by nobody.
        checksum += readOwner(target);
        checksum += readOwner(makeOwner(n + 6));

        // A field, replaced every round.
        keeper.replace(n);
        checksum += keeper.reading();

        // A slot, and an array that owns what it holds.
        Owner[] slots = new Owner[2];
        unsafeArraySet(slots, 0, makeOwner(n + 7));
        unsafeArraySet(slots, 1, makeOwner(n + 8));
        checksum += readOwner(slots[0]) + readOwner(slots[1]);
        Owner[] literal = {{ makeOwner(n + 9) }};
        checksum += readOwner(literal[0]);

        // A subscriber holds nothing, so a struct around one is an ordinary
        // copyable value and goes everywhere a shared value goes.
        Node* node = new Node(n % 100003);
        Watcher first;
        first.node = node;
        first.tag = n % 100003;
        Watcher second = first;
        Watcher third = left ? first : second;
        Watcher[] watchers = {{ first, second }};
        Watcher framed[2] = {{ first, third }};
        checksum += readWatcher(second) + readWatcher(third);
        checksum += readWatcher(watchers[1]) + readWatcher(framed[0]);

        // A weak reference is cleared with its target, copies included.
        Weakly watched;
        watched.node = node;
        Weakly copiedWeak = watched;
        checksum += copiedWeak.node.value;
        delete node;
        if (watched.node == null) {{ checksum += 1; }}
        if (copiedWeak.node == null) {{ checksum += 2; }}

        checksum = checksum % 1000003;
        round += 1;
    }}

    checksum += keeper.reading() + readOwner(target);
    delete keeper;
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_flowing(seed: int, std: Path) -> str:
    """Counted values crossing statement boundaries.

    The `counted` shape carries a value whose parts are counted through the
    places a *copy* happens; this one carries it through the places control
    *leaves* -- an early exit from a loop, an unwind, a deferred body, the arm
    of a branch -- and through a loop header that made what it iterates over.
    That is where three defects lived that no expression-shaped program could
    reach: a foreach released nothing of an array its own header built, a
    foreach over a collection ran that header twice, and the loop variable was
    neither half of a name, so iterating the same array twice was a
    use-after-free.

    Every loop below runs at least twice over the same container, because one
    missing count is only visible on the second pass.
    """
    rng = random.Random(seed)
    rounds = rng.randint(3, 14)
    step = rng.randint(1, 7)
    bias = rng.randint(1, 23)
    width = rng.randint(1, 4)
    library = (std / "collections" / "vector.abs").as_posix()
    text_library = (std / "string.abs").as_posix()

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape flowing.
import "{library}";
import "{text_library}";

struct Entry {{ public string name; public int64 weight; }}

int64 fold(string text) {{
    int32 count = std.text.codePointCount(text);
    int64 total = count;
    int32 index = 0;
    while (index < count) {{
        total = (total * 31 + std.text.codePointAt(text, index)) % 100003;
        index += 1;
    }}
    return total;
}}

string label(int64 n) {{
    string result = "";
    int64 index = 0;
    while (index < n % {width} + 1) {{
        result = std.text.concat(result, "ab");
        index += 1;
    }}
    return result;
}}

Entry entryOf(int64 n) {{
    Entry made;
    made.name = label(n);
    made.weight = n % 100003;
    return made;
}}

int64 weigh(Entry entry) {{ return (fold(entry.name) + entry.weight) % 100003; }}

string[] labels(int64 n) {{
    string[] made = new string[3];
    made[0] = label(n);
    made[1] = label(n + 1);
    made[2] = label(n + 2);
    return made;
}}

std.collections.Vector<string>* collect(int64 n) {{
    std.collections.Vector<string>* items = new std.collections.Vector<string>();
    items.push(label(n));
    items.push(label(n + 1));
    return items;
}}

int32 main() {{
    int64 checksum = 0;
    string kept = label({bias});
    std.collections.Vector<string>* shared = collect({bias});
    string[] fixed = labels({bias});

    int32 round = 0;
    while (round < {rounds}) {{
        int64 n = round * {step} + {bias};
        bool left = round % 2 == 0;

        // A loop over a source the header made, and over one it named. Twice
        // each, because a count taken once too often shows on the second pass.
        foreach (string text in labels(n)) {{ checksum += fold(text); }}
        foreach (string text in labels(n)) {{ checksum += fold(text); }}
        foreach (string text in fixed) {{ checksum += fold(text); }}
        foreach (string text in fixed) {{ checksum += fold(text); }}
        foreach (string text in {{ "one", "two" }}) {{ checksum += fold(text); }}
        foreach (string text in collect(n)) {{ checksum += fold(text); }}
        foreach (string text in shared) {{ checksum += fold(text); }}
        foreach (string text in shared) {{ checksum += fold(text); }}

        // Leaving early, on both paths a loop has.
        foreach (string text in labels(n)) {{
            Entry made = entryOf(n);
            if (left) {{ checksum += weigh(made); break; }}
            checksum += fold(text);
        }}
        foreach (string text in fixed) {{
            string local = label(n);
            if (fold(local) % 2 == 0) {{ continue; }}
            checksum += fold(text);
        }}

        // An unwind with counted values in flight, and a deferred body that
        // makes one of its own.
        try {{
            Entry made = entryOf(n + 1);
            string local = label(n + 2);
            defer {{ checksum += fold(local); }}
            if (left) {{ throw new Error(local); }}
            checksum += weigh(made);
        }}
        catch (Error* problem) {{
            checksum += fold(problem.message);
            delete problem;
        }}

        // The arms of a branch, each with a name of its own.
        if (left) {{ Entry made = entryOf(n + 3); checksum += weigh(made); }}
        else {{ string local = label(n + 3); checksum += fold(local); }}

        switch (round % 2) {{
            case 0: {{ Entry made = entryOf(n + 4); checksum += weigh(made); }}
            default: {{ string local = label(n + 4); checksum += fold(local); }}
        }}

        // A conditional whose arms disagree about who holds what.
        string chosen = left ? label(n + 5) : kept;
        checksum += fold(chosen);

        checksum = checksum % 1000003;
        round += 1;
    }}

    checksum += fold(kept) + fold(fixed[0]);
    delete shared;
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_nested_generics(seed: int) -> str:
    """A generic instantiated with a generic: the specialization of the outer
    type has to specialize the inner one it names."""
    rng = random.Random(seed)
    size = rng.randint(2, 12)
    rounds = rng.randint(2, 10)
    step = rng.randint(1, 7)
    bias = rng.randint(1, 37)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape nested.
class Cell<T> {{
    public T held;
    public Cell(T value) {{ held = value; }}
    // Not named get/set: those are property keywords.
    public T read() {{ return held; }}
    public void write(T value) {{ held = value; }}
}}

// The nesting is a generic field of a generic type. It is deliberately not an
// array of them: an array never releases what its elements own, so a
// `Cell<T>*[]` would leak every element and the runtime would abort at exit
// (docs/known-defects.md).
class Row<T> {{
    public T[] values;
    public Cell<T>* latest;

    public Row(int32 size, T initial) {{
        values = new T[size];
        latest = new Cell<T>(initial);
        int32 index = 0;
        while (index < size) {{
            values[index] = initial;
            index += 1;
        }}
    }}

    public T at(int32 index) {{ return values[index % values.length]; }}

    public void put(int32 index, T value) {{
        values[index % values.length] = value;
        latest.write(value);
    }}

    public T newest() {{ return latest.read(); }}
}}

T pass<T>(T value) {{ return value; }}

int32 main() {{
    int64 checksum = 0;

    Cell<int64>* wide = new Cell<int64>({bias});
    Cell<int32>* narrow = new Cell<int32>({bias});
    checksum += wide.read() + narrow.read();
    wide.write(pass<int64>({bias} * 2));
    narrow.write({bias} + 1);
    checksum += wide.read() + narrow.read();
    delete wide;
    delete narrow;

    Row<int64>* row = new Row<int64>({size}, {bias});
    int32 round = 0;
    while (round < {rounds}) {{
        int32 index = 0;
        while (index < {size}) {{
            row.put(index, (round * {step} + index + {bias}) % 100003);
            checksum += row.at(index) + row.newest();
            checksum = checksum % 1000003;
            index += 1;
        }}
        round += 1;
    }}
    delete row;
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_handles(seed: int) -> str:
    """The ownership model itself: one generic container over an element type
    that owns something and over one that does not, plus the subscriber form of
    the same handle, an array of owners, and strings in a container.

    This is where the last three defects lived and none of the other shapes go.
    `Slots<T>` never mentions ownership -- what an element costs to release is
    the element type's answer -- so the same body has to release twenty objects
    for `Node*`, release nothing for `sub Node*`, and emit no drop at all for
    `int64`. Under the leak check, which is the half of the question a checksum
    cannot ask: whether what was built was also given back.
    """
    rng = random.Random(seed)
    rounds = rng.randint(2, 9)
    filled = rng.randint(2, 14)
    step = rng.randint(1, 11)
    bias = rng.randint(1, 53)
    removeAt = rng.randint(0, 1)
    clearFirst = rng.randint(0, 1)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape handles.
// The checksum is built from values read back, so it says the container kept
// what it was given; the leak check says it also gave it back.
class Node {{
    public int64 value;
    public Node(int64 initial) {{ value = initial; }}
}}

class Slots<T> {{
    private T[] items;
    private int32 _count;
    private int32 _capacity;

    public Slots() {{ _count = 0; _capacity = 2; items = new T[2]; }}

    public int32 count {{ get {{ return _count; }} }}

    public void push(T element) {{
        if (_count == _capacity) {{
            int32 grown = _capacity * 2;
            T[] larger = new T[grown];
            unsafeArrayMove(larger, items, _count);
            items = move(larger);
            _capacity = grown;
        }}
        unsafeArraySet(items, _count, move(element));
        _count = _count + 1;
    }}

    // An indexer, not a method: a managed pointer handed back from a call is a
    // transfer, and reading through a container is not the container giving the
    // element up.
    public nothrow sub T this[int32 index] {{
        get {{
            assert((index as uint32) < (_count as uint32), "index in range");
            return unsafeArrayGet(items, index);
        }}
    }}

    public T take() {{
        assert(_count > 0, "take from a non-empty container");
        _count = _count - 1;
        return unsafeArrayTake(items, _count);
    }}

    public void removeAt(int32 index) {{
        assert((index as uint32) < (_count as uint32), "removeAt in range");
        unsafeArrayDrop(items, index, 1);
        int32 i = index;
        while (i < _count - 1) {{
            unsafeArraySet(items, i, unsafeArrayTake(items, i + 1));
            i = i + 1;
        }}
        _count = _count - 1;
    }}

    public void clear() {{
        unsafeArrayDrop(items, 0, _count);
        _count = 0;
    }}
}}

int32 main() {{
    int64 checksum = 0;
    int32 round = 0;
    while (round < {rounds}) {{
        // Owners: the container releases every element it still holds.
        Slots<Node*>* owners = new Slots<Node*>();
        int32 i = 0;
        while (i < {filled}) {{
            owners.push(new Node(i * {step} + {bias} + round));
            i = i + 1;
        }}
        checksum += owners[0].value + owners[{filled} - 1].value;

        // A take hands one out, and the caller is the one that releases it.
        Node* taken = owners.take();
        checksum += taken.value;
        delete taken;

        if ({removeAt} == 1 && owners.count > 1) {{
            owners.removeAt(0);
            checksum += owners[0].value;
        }}
        if ({clearFirst} == 1) {{ owners.clear(); }}
        checksum = checksum % 1000003;
        delete owners;

        // The identical body over a subscriber, which owns nothing: the
        // objects below outlive the container that borrowed them.
        Node* first = new Node(round + {bias});
        Node* second = new Node(round * {step} + 1);
        Slots<sub Node*>* borrowed = new Slots<sub Node*>();
        borrowed.push(first);
        borrowed.push(second);
        checksum += borrowed[0].value + borrowed[1].value;
        delete borrowed;
        checksum += first.value + second.value;
        delete first;
        delete second;

        // And over an element with nothing to release, where the drop is not
        // emitted at all.
        Slots<int64>* numbers = new Slots<int64>();
        int32 n = 0;
        while (n < {filled}) {{
            numbers.push(n + round);
            n = n + 1;
        }}
        checksum += numbers[{filled} - 1] + numbers.take();
        numbers.clear();
        delete numbers;

        // A bare array of owners, released where it goes out of scope.
        {{
            Node*[] block = new Node*[{filled}];
            int32 b = 0;
            while (b < {filled}) {{
                unsafeArraySet(block, b, new Node(b + round));
                b = b + 1;
            }}
            checksum += block[{filled} - 1].value;
            // A literal owns its elements the same way.
            Node*[] pair = {{ new Node(round), new Node(round + 1) }};
            checksum += pair[1].value;
        }}

        checksum = checksum % 1000003;
        round += 1;
    }}

    println(checksum % 1000003);
    return 0;
}}
"""


def generate_carry(seed: int) -> str:
    """Owners carried out of a scope the hard ways: by `defer` on both exits,
    and by a `throw` that unwinds a frame still holding them.

    The `unwind` shape throws with objects in flight but its defers only touch
    a raw counter, and the `handles` shape owns things but never leaves a frame
    the unusual way. Where those two meet is the entry point's own exit path,
    which returned a fixed-width value and made a `void main()` with a `try` in
    it fail to compile at all.
    """
    rng = random.Random(seed)
    rounds = rng.randint(3, 14)
    held = rng.randint(1, 5)
    modulus = rng.randint(2, 5)
    step = rng.randint(1, 9)
    bias = rng.randint(1, 61)
    nested = rng.randint(0, 1)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape carry.
// Every owner made here is released exactly once, on whichever way out of the
// frame the round takes; the leak check says so and the checksum says the
// values survived long enough to be read.
class Node {{
    public int64 value;
    public Node(int64 initial) {{ value = initial; }}
}}

class Bag {{
    public Node*[] items;
    public int32 filled;

    public Bag(int32 size) {{
        items = new Node*[size];
        filled = 0;
    }}

    public void add(Node* node) {{
        unsafeArraySet(items, filled, move(node));
        filled = filled + 1;
    }}

    public int64 first() {{ return items[0].value; }}
}}

// A frame that may leave by return or by throw, holding a container of owners
// and a loose one, both released by `defer` either way.
int64 carry(int64 round) {{
    Bag* bag = new Bag({held});
    defer delete bag;

    int32 i = 0;
    while (i < {held}) {{
        bag.add(new Node(round * {step} + i + {bias}));
        i = i + 1;
    }}

    Node* loose = new Node(round + {bias});
    defer delete loose;

    if (round % {modulus} == 0) {{
        throw new Error("unwound while holding owners");
    }}
    return (bag.first() + loose.value) % 1000003;
}}

int64 nestedCarry(int64 round) {{
    Node* outer = new Node(round + 1);
    defer delete outer;
    try {{
        return carry(round) + outer.value;
    }} catch (Error* inner) {{
        // Caught one frame in, and the owner this frame holds is still live.
        return outer.value;
    }}
}}

// The entry point returns nothing: its exit status is a status, not a value,
// and a `try` in here is what used to make the program fail to compile.
void main() {{
    int64 checksum = 0;
    int64 caught = 0;
    int64 round = 0;
    while (round < {rounds}) {{
        try {{
            if ({nested} == 1) {{ checksum += nestedCarry(round); }}
            else {{ checksum += carry(round); }}
        }} catch (Error* failure) {{
            caught += 1;
        }}
        checksum = checksum % 1000003;
        round += 1;
    }}

    // An owner released by a defer at the end of this frame as well, so the
    // entry point is not the one shape that never holds anything.
    Node* last = new Node(checksum % 97);
    defer delete last;
    checksum = (checksum + last.value + caught) % 1000003;

    println(checksum % 1000003);
}}
"""


def generate_text(seed: int, std: Path) -> str:
    """Strings: built, joined, sliced, compared, searched. Under the leak check
    like every other shape now that a string has a lifetime: a generated
    program builds hundreds of them, so one that is not released shows up as
    hundreds of reported leaks."""
    rng = random.Random(seed)
    rounds = rng.randint(3, 20)
    width = rng.randint(1, 6)
    bias = rng.randint(1, 41)
    needle = rng.choice(("ab", "ba", "aa", "b"))
    library = (std / "string.abs").as_posix()

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape text.
// The checksum is built from counts, code points and comparison results, so
// the answer is a number and does not depend on how a string prints.
import "{library}";

int64 fold(string text) {{
    int32 count = std.text.codePointCount(text);
    int64 total = count;
    int32 index = 0;
    while (index < count) {{
        total = (total * 31 + std.text.codePointAt(text, index)) % 1000003;
        index += 1;
    }}
    return total;
}}

string build(int32 count) {{
    string result = "";
    int32 index = 0;
    while (index < count) {{
        // Alternating pieces, so the result is not one repeated character.
        if (index % 2 == 0) {{ result = std.text.concat(result, "ab"); }}
        else {{ result = std.text.concat(result, "b"); }}
        index += 1;
    }}
    return result;
}}

int32 main() {{
    int64 checksum = 0;
    int32 round = 0;
    while (round < {rounds}) {{
        string made = build(round % {width} + 1);
        int32 count = std.text.codePointCount(made);
        checksum += fold(made);

        // Boundaries, not typical values: the whole string, an empty piece at
        // the end, one character, and the last character.
        checksum += fold(std.text.substring(made, 0, count));
        checksum += fold(std.text.substring(made, count, 0));
        if (count > 0) {{
            checksum += fold(std.text.substring(made, 0, 1));
            checksum += fold(std.text.substring(made, count - 1, 1));
        }}

        checksum += std.text.indexOf(made, "{needle}") + 2;
        checksum += std.text.lastIndexOf(made, "{needle}") + 2;
        checksum += fold(std.text.toUpper(made)) + fold(std.text.toLower(made));
        checksum += fold(std.text.replace(made, "a", ""));
        checksum += fold(std.text.trim(made));
        checksum += fold(std.text.repeat(made, round % 3));
        if (std.text.contains(made, "{needle}")) {{ checksum += 3; }}
        if (std.text.startsWith(made, "a")) {{ checksum += 5; }}
        if (std.text.endsWith(made, "b")) {{ checksum += 7; }}
        if (std.text.isEmpty(made)) {{ checksum += 11; }}
        if (made == build(round % {width} + 1)) {{ checksum += {bias}; }}
        checksum = checksum % 1000003;
        round += 1;
    }}
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_widths(seed: int) -> str:
    """Conversions between integer widths and to floating point, with values
    chosen to fit, so every answer is unambiguous at every level."""
    rng = random.Random(seed)
    rounds = rng.randint(4, 30)
    step = rng.randint(1, 97)
    bias = rng.randint(1, 113)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape widths.
// Every value here fits the type it is put into, so the answer does not depend
// on what truncation would do -- the question is whether the same value
// survives the trip through each width, signed and unsigned.
int64 widen(int8 tiny, int16 small, int32 medium) {{
    int64 total = tiny;
    total += small;
    total += medium;
    return total;
}}

int64 unsignedTrip(uint8 tiny, uint16 small, uint32 medium) {{
    uint64 total = tiny;
    total += small;
    total += medium;
    return total as int64;
}}

double asFloating(int32 value) {{
    // An int32 is exactly representable in a double, so this trip is lossless
    // and the comparison below is not a floating tolerance question.
    double scaled = value;
    return scaled;
}}

int32 main() {{
    int64 checksum = 0;
    int32 round = 0;
    while (round < {rounds}) {{
        int8 tiny = (round % 100 + 1) as int8;
        int16 small = (round * {step} % 30000 + 1) as int16;
        int32 medium = round * {step} + {bias};

        checksum += widen(tiny, small, medium);
        checksum += unsignedTrip(
            (round % 200 + 1) as uint8,
            (round * {step} % 60000 + 1) as uint16,
            (round * {step} + {bias}) as uint32);

        // Down and back up again: a value that fits must come back unchanged.
        int64 wide = medium;
        int32 narrowed = wide as int32;
        if (narrowed != medium) {{ println(-1); return 1; }}
        checksum += narrowed;

        double floating = asFloating(medium);
        if ((floating as int32) != medium) {{ println(-2); return 1; }}
        checksum += floating as int64;

        // Signed and unsigned of the same width disagree only above the signed
        // maximum, and these values are below it, so they must agree here.
        uint32 unsignedMedium = medium as uint32;
        if ((unsignedMedium as int32) != medium) {{ println(-3); return 1; }}
        checksum += unsignedMedium as int64;

        checksum = checksum % 1000003;
        round += 1;
    }}
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_slices(seed: int) -> str:
    """Slices: of an array, of a slice, written through, and passed. A slice
    shares the buffer it came from, which is what makes it worth checking."""
    rng = random.Random(seed)
    size = rng.randint(8, 40)
    rounds = rng.randint(2, 12)
    step = rng.randint(1, 7)
    bias = rng.randint(1, 61)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape slices.
int64 sum(int64[] values) {{
    int64 total = 0;
    int32 index = 0;
    while (index < values.length) {{
        total += values[index];
        index += 1;
    }}
    return total % 100003;
}}

// A borrowed view: writing through it reaches the array it came from, and the
// caller must see that.
void bump(int64[] view, int64 amount) {{
    int32 index = 0;
    while (index < view.length) {{
        view[index] = (view[index] + amount) % 100003;
        index += 1;
    }}
}}

int32 main() {{
    int64 checksum = 0;
    int64[] values = new int64[{size}];
    int32 index = 0;
    while (index < {size}) {{
        values[index] = (index * {step} + {bias}) % 100003;
        index += 1;
    }}

    int32 round = 0;
    while (round < {rounds}) {{
        int32 begin = round % ({size} / 2);
        int32 end = begin + {size} / 2;
        int64[] window = values[begin:end];
        checksum += window.length;
        checksum += sum(window);

        // A slice of a slice: the second one is relative to the first, and
        // both still refer to the original buffer.
        if (window.length >= 2) {{
            int64[] inner = window[1:window.length];
            checksum += inner.length + sum(inner);
            if (inner[0] != window[1]) {{ println(-1); return 1; }}
        }}

        bump(window, round + 1);
        // The write went through to the array, not to a copy of it.
        if (values[begin] != window[0]) {{ println(-2); return 1; }}
        checksum += sum(values);
        checksum = checksum % 1000003;
        round += 1;
    }}
    println(checksum % 1000003);
    return 0;
}}
"""


# Each shape exercises a different part of the backend, and the seed picks
# which one, so a run with N cases covers all of them rather than N variations
# of the same program.
# The third entry says whether the shape's leaks are expected. None are: the
# text shape needed it while a string had no lifetime, and does not now
# (docs/known-defects.md section 1). It is kept because the next shape that
# needs it should say so here rather than turning the check off for everything.
SHAPES = (
    ("board", generate_board, False),
    ("dispatch", generate_dispatch, False),
    ("unwind", generate_unwind, False),
    ("closures", generate_closures, False),
    ("generics", generate_generics, False),
    ("values", generate_values, False),
    ("control", generate_control, False),
    ("accessors", generate_accessors, False),
    ("weak", generate_weak, False),
    ("aggregates", generate_aggregates, False),
    ("nested", generate_nested_generics, False),
    ("text", generate_text, False),
    ("widths", generate_widths, False),
    ("slices", generate_slices, False),
    ("handles", generate_handles, False),
    ("carry", generate_carry, False),
    ("counted", generate_counted, False),
    ("owned", generate_owned, False),
    ("flowing", generate_flowing, False),
)

# Two shapes need the standard library -- one builds strings and one counts
# what an aggregate holding them names -- so they are the two dropped when the
# caller cannot say where the library is.
NEEDS_STANDARD_LIBRARY = frozenset({"text", "counted", "flowing"})


def generate(seed: int, shapes, std: Path | None) -> tuple[str, str, bool]:
    name, builder, leaks = shapes[seed % len(shapes)]
    program = builder(seed, std) if name in NEEDS_STANDARD_LIBRARY else builder(seed)
    return name, program, leaks


def run(command: list[str], timeout: int, environment: dict | None = None):
    # Closed standard input rather than the runner's, so a generated program
    # can never block on a terminal that happens to be attached.
    return subprocess.run(command, capture_output=True, text=True,
                          encoding="utf-8", errors="replace", timeout=timeout,
                          check=False, env=environment,
                          stdin=subprocess.DEVNULL)


SANITIZER_MARKERS = ("AddressSanitizer", "LeakSanitizer", "runtime error:",
                     "memory leak detected", "managed pointer(s) leaked")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path, required=True)
    parser.add_argument("--cases", type=int, default=12)
    parser.add_argument("--seed", type=int, default=20260818)
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--configuration", default="")
    # Where the platform's sanitizer has no leak checker -- Windows, Termux --
    # the run still checks the other two things it can: that the program
    # touched no memory it should not have, and that -O0 and -O3 agree.
    parser.add_argument("--detect-leaks", default="1",
                        choices=("0", "1", "ON", "OFF"))
    parser.add_argument("--std-dir", type=Path, default=None,
                        help="the standard library directory; without it the "
                             "string shape is left out rather than guessed at")
    args = parser.parse_args()

    work = args.work_dir.resolve()
    work.mkdir(parents=True, exist_ok=True)
    compiler = args.compiler.resolve()
    leaks = "1" if args.detect_leaks in ("1", "ON") else "0"
    checking = os.environ.copy()
    checking["ASAN_OPTIONS"] = f"detect_leaks={leaks}:abort_on_error=0"
    # For a shape whose leaks are expected, everything else the sanitizer
    # answers still counts.
    permissive = os.environ.copy()
    permissive["ASAN_OPTIONS"] = "detect_leaks=0:abort_on_error=0"

    std = args.std_dir.resolve() if args.std_dir else None
    shapes = [shape for shape in SHAPES
              if std or shape[0] not in NEEDS_STANDARD_LIBRARY]

    failures = 0
    for index in range(args.cases):
        seed = args.seed + index
        shape, program, leaksByDesign = generate(seed, shapes, std)
        source = work / f"case-{seed}-{shape}.abs"
        source.write_text(program, encoding="utf-8")

        answers = {}
        for level, sanitize in (("O0", True), ("O3", False)):
            binary = work / f"case-{seed}-{level}"
            command = [str(compiler), str(source), f"-{level}", "--build-exe",
                       "-o", str(binary)]
            if sanitize:
                command.insert(2, "--sanitize=address")
            build = run(command, args.timeout)
            if build.returncode != 0:
                print(f"BUILD FAILED seed={seed} shape={shape} level={level}")
                print(build.stdout[-800:] + build.stderr[-800:])
                failures += 1
                break
            result = run([str(binary)], args.timeout,
                         permissive if leaksByDesign else checking)
            output = result.stdout + result.stderr
            if result.returncode != 0 or any(
                    marker in output for marker in SANITIZER_MARKERS):
                print(f"RUN FAILED seed={seed} shape={shape} level={level} "
                      f"exit={result.returncode}")
                print(output[-1200:])
                print(f"    reproduce: {source}")
                failures += 1
                break
            answers[level] = result.stdout.strip()
        else:
            if len(set(answers.values())) > 1:
                print(f"DISAGREEMENT seed={seed} shape={shape}: {answers}")
                print(f"    reproduce: {source}")
                failures += 1

    print(f"codegen-fuzz={'ok' if failures == 0 else 'failed'} "
          f"cases={args.cases} shapes={len(shapes)} "
          f"seed={args.seed} failures={failures} "
          f"configuration={args.configuration}")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
