#!/usr/bin/env python3
"""Generate valid typed programs and run them under AddressSanitizer.

The corpora that exist generate one shape each -- integer mixing, floating
arithmetic, integer edges, ownership operations -- and none of them is compiled
with a sanitizer. What the backend actually emits for the rest of the language
is never fuzzed: arrays with computed indices, classes with fields and methods,
managed owners created and deleted while a loop runs over them, nested control
flow that decides which of those happens.

Every program here is valid by construction and self-checking by construction:
it accumulates a checksum from what it did and prints it. The oracle is
agreement rather than a model -- the same program at -O0 and at -O3 must print
the same number -- plus the sanitizer and the runtime's own leak check, which
answer a different question: not "is the number right" but "did the program
touch memory it should not have, or leave some behind".

A model in Python would be a second implementation of the semantics, able to be
wrong on its own; the two oracles here cannot be wrong, only silent.
"""

from __future__ import annotations

import argparse
import os
import random
import subprocess
import sys
from pathlib import Path


def generate_board(seed: int) -> str:
    """A class with an array field, a managed owner, loops and recursion."""
    rng = random.Random(seed)
    size = rng.randint(4, 32)
    rounds = rng.randint(2, 12)
    step = rng.randint(1, 7)
    bias = rng.randint(1, 97)
    threshold = rng.randint(1, max(2, size - 1))
    depth = rng.randint(1, 3)

    # Every index is computed and then brought back into range by a remainder,
    # so the program is valid however the constants fall.
    body = f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}.
class Cell {{
    public int32 value;
    public Cell(int32 initial) {{ value = initial; }}
    public int32 mixed(int32 salt) {{ return (value * 3 + salt) % 100003; }}
}}

class Board {{
    public int32[] cells;
    public int32 count;
    public Cell* marker;

    public Board(int32 size) {{
        cells = new int32[size];
        count = size;
        marker = new Cell({bias});
        int32 index = 0;
        while (index < count) {{
            cells[index] = (index * {step} + {bias}) % 1009;
            index += 1;
        }}
    }}

    public int64 sweep(int32 round) {{
        int64 total = 0;
        int32 index = 0;
        while (index < count) {{
            int32 probe = (index * {step} + round) % count;
            int32 current = cells[probe];
            if (current % 2 == 0) {{
                cells[probe] = current + round;
                total += current;
            }}
            else {{
                cells[probe] = current - 1;
                total -= 1;
            }}
            if (probe < {threshold}) {{
                total += marker.mixed(current % 97);
            }}
            index += 1;
        }}
        return total;
    }}

    // The managed field is released by the object's own destructor, in reverse
    // declaration order; a hook that deleted it would be deleting a subscriber.
    public void destroy() {{ count = 0; }}
}}

int64 nested(int32 value, int32 level) {{
    if (level <= 0) {{ return value % 5003; }}
    int64 folded = 0;
    int32 index = 0;
    while (index < 4) {{
        folded += nested(value + index * {step}, level - 1);
        index += 1;
    }}
    return folded % 100019;
}}

int32 main() {{
    int64 checksum = 0;
    Board* board = new Board({size});
    int32 round = 0;
    while (round < {rounds}) {{
        checksum += board.sweep(round);
        checksum = checksum % 1000003;
        round += 1;
    }}
    delete board;

    // A local array, an owner that outlives a loop, and one that does not.
    int32[] scratch = new int32[{size}];
    int32 index = 0;
    while (index < {size}) {{
        Cell* cell = new Cell(index * {step} + {bias});
        scratch[index] = cell.mixed(index % 89);
        checksum += scratch[index];
        delete cell;
        index += 1;
    }}
    checksum += nested({bias}, {depth});
    // Printed as a number rather than through `format`, so the leak check
    // stays meaningful: a string has no lifetime yet (docs/known-defects.md)
    // and every `format` call would leak its buffer into the report.
    println(checksum % 1000003);
    return 0;
}}
"""
    return body


def generate_dispatch(seed: int) -> str:
    """Virtual dispatch: an interface, several implementations, a loop over
    an array of owners that calls through the vtable."""
    rng = random.Random(seed)
    count = rng.randint(3, 24)
    rounds = rng.randint(2, 8)
    weights = [rng.randint(1, 40) for _ in range(3)]
    offset = rng.randint(1, 61)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape dispatch.
interface IScore {{
    int64 score(int64 input);

    // A default body calling the rest of the contract has to reach the
    // concrete implementation through the vtable, not the declaration.
    int64 doubled(int64 input) {{ return score(input) * 2; }}
}}

class Flat : IScore {{
    public int64 bias;
    public Flat(int64 value) {{ bias = value; }}
    public virtual int64 score(int64 input) {{
        return (input + bias) % 100003;
    }}
}}

class Scaled : Flat {{
    public int64 factor;
    public Scaled(int64 value, int64 scale) {{
        base(value);
        factor = scale;
    }}
    // Overrides an override: the vtable slot the interface names has to reach
    // this body, not the one the base class installed.
    public virtual int64 score(int64 input) {{
        return ((input + bias) * factor) % 100003;
    }}
}}

class Folded : IScore {{
    public int64[] history;
    public int64 cursor;
    public Folded(int32 size) {{
        history = new int64[size];
        cursor = 0;
    }}
    public virtual int64 score(int64 input) {{
        history[cursor % history.length] = input;
        cursor += 1;
        int64 total = 0;
        int32 index = 0;
        while (index < history.length) {{
            total += history[index];
            index += 1;
        }}
        return total % 100003;
    }}
}}

int64 through(IScore* subject, int64 input) {{
    // Reached as an interface, so every call is a vtable call.
    return subject.doubled(input) + subject.score(input + 1);
}}

int32 main() {{
    int64 checksum = 0;
    int32 index = 0;
    while (index < {count}) {{
        IScore* subject = null;
        if (index % 3 == 0) {{ subject = new Flat(index * {weights[0]} + {offset}); }}
        else if (index % 3 == 1) {{ subject = new Scaled(index + {weights[1]}, {weights[2]}); }}
        else {{ subject = new Folded(index % 5 + 1); }}

        int32 round = 0;
        while (round < {rounds}) {{
            checksum += through(subject, index * round + {offset});
            checksum = checksum % 1000003;
            round += 1;
        }}
        delete subject;
        index += 1;
    }}
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_unwind(seed: int) -> str:
    """Exceptions: owners in flight when a throw leaves a frame, defer and
    finally on the way out, a catch that folds the failure into the answer."""
    rng = random.Random(seed)
    depth = rng.randint(1, 4)
    trips = rng.randint(2, 16)
    modulus = rng.randint(2, 7)
    bias = rng.randint(1, 89)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape unwind.
class Failure : Error {{
    public int64 code;
    public Failure(string text, int64 value) {{
        base(text);
        code = value;
    }}
}}

class Holder {{
    public int64[] cells;
    public int64 total;
    public Holder(int32 size, int64 seed) {{
        cells = new int64[size];
        int32 index = 0;
        while (index < size) {{
            cells[index] = (index * seed + {bias}) % 1009;
            index += 1;
        }}
        total = 0;
    }}
    public int64 fold() {{
        int32 index = 0;
        while (index < cells.length) {{
            total += cells[index];
            index += 1;
        }}
        return total % 100003;
    }}
}}

// The owner is alive when the throw happens, so leaving through the exception
// path has to release exactly what leaving through the return path releases.
int64 descend(int64 value, int32 level, raw int64* visits) {{
    Holder* holder = new Holder(level + 2, value);
    defer {{ *visits += 1; }}
    int64 folded = holder.fold();
    if (level <= 0) {{
        if (value % {modulus} == 0) {{
            delete holder;
            throw new Failure("bottom", folded);
        }}
        delete holder;
        return folded;
    }}
    try {{
        int64 deeper = descend(value + level, level - 1, visits);
        delete holder;
        return (folded + deeper) % 100003;
    }}
    catch (Failure* failure) {{
        int64 recovered = (folded + failure.code) % 100003;
        delete holder;
        return recovered;
    }}
}}

int32 main() {{
    int64 checksum = 0;
    int64 visits = 0;
    raw int64* visitCount = &visits;
    int32 trip = 0;
    while (trip < {trips}) {{
        try {{
            checksum += descend(trip + {bias}, {depth}, visitCount);
        }}
        catch (Failure* failure) {{
            checksum += failure.code + 1;
        }}
        checksum = checksum % 1000003;
        trip += 1;
    }}
    println((checksum + visits) % 1000003);
    return 0;
}}
"""


def generate_closures(seed: int) -> str:
    """Lambdas: captured locals, a closure stored and called after the value it
    captured changed, closures handed to and returned from functions."""
    rng = random.Random(seed)
    rounds = rng.randint(4, 40)
    step = rng.randint(1, 9)
    bias = rng.randint(1, 73)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape closures.
func<int64, int64> adder(int64 amount) {{
    // Escapes the frame that made it, so the capture outlives its source.
    return fn(int64 value) => (value + amount) % 100003;
}}

int64 applyTwice(func<int64, int64> operation, int64 value) {{
    return operation(operation(value));
}}

int64 accumulate(func<int64, int64> operation, int32 count, int64 start) {{
    int64 total = start;
    int32 index = 0;
    while (index < count) {{
        total = (total + operation(index)) % 100003;
        index += 1;
    }}
    return total;
}}

int32 main() {{
    int64 checksum = 0;
    int64 captured = {bias};
    func<int64, int64> scale = fn(int64 value) => (value * {step} + captured) % 100003;
    // A copy keeps the environment it was made with; reassignment releases the
    // old owner rather than the copy's.
    func<int64, int64> copied = scale;
    captured = {bias} * 2;
    scale = fn(int64 value) => (value + {step}) % 100003;

    checksum += applyTwice(copied, {bias});
    checksum += applyTwice(scale, {bias});
    checksum = checksum % 1000003;

    func<int64, int64> escaped = adder({bias});
    checksum += accumulate(escaped, {rounds}, checksum);
    checksum = checksum % 1000003;

    int32 index = 0;
    while (index < {rounds}) {{
        // A fresh closure on every iteration: the scope releases each one as
        // it closes, rather than the last one only.
        int64 local = index * {step};
        func<int64, int64> perRound = fn(int64 value) => (value + local) % 100003;
        checksum += perRound(index);
        checksum = checksum % 1000003;
        index += 1;
    }}
    println(checksum % 1000003);
    return 0;
}}
"""


def generate_generics(seed: int) -> str:
    """Generics: one function and one class specialized at several widths, so
    the same source produces several bodies that must each be right."""
    rng = random.Random(seed)
    size = rng.randint(3, 20)
    step = rng.randint(1, 11)
    bias = rng.randint(1, 53)

    return f"""// Generated by tools/testing/codegen_fuzz.py, seed {seed}, shape generics.
T pick<T>(T[] values, int32 index) {{
    return values[index % values.length];
}}

// Values of an unconstrained type parameter are moved around, not computed
// with: the language has no numeric constraint to say `T + T` is allowed.
T[] pair<T>(T left, T right) {{
    T[] made = new T[2];
    made[0] = left;
    made[1] = right;
    return made;
}}

class Box<T> {{
    public T[] items;
    public int32 used;

    public Box(int32 size) {{
        items = new T[size];
        used = 0;
    }}

    public void put(T value) {{
        items[used % items.length] = value;
        used += 1;
    }}

    public T at(int32 index) {{
        return items[index % items.length];
    }}
}}

int32 main() {{
    int64 checksum = 0;

    int32[] narrow = new int32[{size}];
    int64[] wide = new int64[{size}];
    int32 index = 0;
    while (index < {size}) {{
        narrow[index] = index * {step} + {bias};
        wide[index] = index * {step} * 1000 + {bias};
        index += 1;
    }}

    index = 0;
    while (index < {size} * 2) {{
        checksum += pick(narrow, index);
        checksum += pick(wide, index) % 100003;
        checksum = checksum % 1000003;
        index += 1;
    }}

    int32[] narrowPair = pair<int32>({bias}, {step});
    int64[] widePair = pair<int64>({bias} * 1000, {step});
    checksum += narrowPair[0] + narrowPair[1];
    checksum += (widePair[0] + widePair[1]) % 100003;
    checksum = checksum % 1000003;

    Box<int32>* narrowBox = new Box<int32>({size});
    Box<int64>* wideBox = new Box<int64>({size});
    index = 0;
    while (index < {size} * 2) {{
        narrowBox.put(index * {step});
        wideBox.put(index * {step} * 100);
        index += 1;
    }}
    index = 0;
    while (index < {size}) {{
        checksum += narrowBox.at(index);
        checksum += wideBox.at(index) % 100003;
        checksum = checksum % 1000003;
        index += 1;
    }}
    delete narrowBox;
    delete wideBox;

    println(checksum % 1000003);
    return 0;
}}
"""


# Each shape exercises a different part of the backend, and the seed picks
# which one, so a run with N cases covers all of them rather than N variations
# of the same program.
SHAPES = (
    ("board", generate_board),
    ("dispatch", generate_dispatch),
    ("unwind", generate_unwind),
    ("closures", generate_closures),
    ("generics", generate_generics),
)


def generate(seed: int) -> tuple[str, str]:
    name, builder = SHAPES[seed % len(SHAPES)]
    return name, builder(seed)


def run(command: list[str], timeout: int, environment: dict | None = None):
    # Closed standard input rather than the runner's, so a generated program
    # can never block on a terminal that happens to be attached.
    return subprocess.run(command, capture_output=True, text=True,
                          encoding="utf-8", errors="replace", timeout=timeout,
                          check=False, env=environment,
                          stdin=subprocess.DEVNULL)


SANITIZER_MARKERS = ("AddressSanitizer", "LeakSanitizer", "runtime error:",
                     "memory leak detected", "managed pointer(s) leaked")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path, required=True)
    parser.add_argument("--cases", type=int, default=12)
    parser.add_argument("--seed", type=int, default=20260818)
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--configuration", default="")
    # Where the platform's sanitizer has no leak checker -- Windows, Termux --
    # the run still checks the other two things it can: that the program
    # touched no memory it should not have, and that -O0 and -O3 agree.
    parser.add_argument("--detect-leaks", default="1",
                        choices=("0", "1", "ON", "OFF"))
    args = parser.parse_args()

    work = args.work_dir.resolve()
    work.mkdir(parents=True, exist_ok=True)
    compiler = args.compiler.resolve()
    environment = os.environ.copy()
    leaks = "1" if args.detect_leaks in ("1", "ON") else "0"
    environment["ASAN_OPTIONS"] = f"detect_leaks={leaks}:abort_on_error=0"

    failures = 0
    for index in range(args.cases):
        seed = args.seed + index
        shape, program = generate(seed)
        source = work / f"case-{seed}-{shape}.abs"
        source.write_text(program, encoding="utf-8")

        answers = {}
        for level, sanitize in (("O0", True), ("O3", False)):
            binary = work / f"case-{seed}-{level}"
            command = [str(compiler), str(source), f"-{level}", "--build-exe",
                       "-o", str(binary)]
            if sanitize:
                command.insert(2, "--sanitize=address")
            build = run(command, args.timeout)
            if build.returncode != 0:
                print(f"BUILD FAILED seed={seed} shape={shape} level={level}")
                print(build.stdout[-800:] + build.stderr[-800:])
                failures += 1
                break
            result = run([str(binary)], args.timeout, environment)
            output = result.stdout + result.stderr
            if result.returncode != 0 or any(
                    marker in output for marker in SANITIZER_MARKERS):
                print(f"RUN FAILED seed={seed} shape={shape} level={level} "
                      f"exit={result.returncode}")
                print(output[-1200:])
                print(f"    reproduce: {source}")
                failures += 1
                break
            answers[level] = result.stdout.strip()
        else:
            if len(set(answers.values())) > 1:
                print(f"DISAGREEMENT seed={seed} shape={shape}: {answers}")
                print(f"    reproduce: {source}")
                failures += 1

    print(f"codegen-fuzz={'ok' if failures == 0 else 'failed'} "
          f"cases={args.cases} seed={args.seed} failures={failures} "
          f"configuration={args.configuration}")
    return 0 if failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
