#!/usr/bin/env python3
"""Model-based generator for ownership operations.

Generates random but legal Absolute programs made of new/alias/weak/move/delete
and checks the compiler and runtime against an independent model of lifetime
state rather than against a hand-written expectation.

The model is the point. It tracks, for every object, whether it is alive and
which places name it, and it applies the ownership rules directly:

  new         a fresh owning place, one live object
  alias       a subscriber; it never owns and expires with the owner
  weak        an observer; it never owns and expires with the object
  move        ownership leaves the source place, which becomes unusable
  delete      the object dies, every alias and weak handle naming it expires,
              and its destructor runs exactly once

Each generated statement is followed by assertions derived from the model: the
truthiness of every live weak handle, and the running count of destructor calls.
A disagreement between the model and the runtime fails the generated program at
the exact statement that diverged, and the program is kept as a reproducer.

Only legal programs are emitted. The generator picks operations from what the
model says is currently allowed, so a moved-from place is never read, a
subscriber is never moved, and nothing is deleted twice. That is deliberate:
rejecting invalid programs is what tests/ownership-torture-cycle-*.abs and the
other error tests are for, while this tool checks that valid ones behave the way
the ownership model says they must.
"""

from __future__ import annotations

import argparse
import os
import random
import subprocess
import sys
from pathlib import Path


PRELUDE = """\
// Generated by tools/testing/ownership_model.py -- do not edit.
// Seed: {seed}

struct Probe {{
    raw int32* counter;

    void arm(raw int32* target) {{
        counter = target;
    }}

    void destroy() {{
        if (counter != null) {{
            *counter = *counter + 1;
        }}
    }}
}}

class Obj {{
    public int32 id;
    public Probe probe;

    public Obj(raw int32* counter, int32 identifier) {{
        id = identifier;
        probe.arm(counter);
    }}
}}

int32 main() {{
    int32 destroyed = 0;
    raw int32* place = &destroyed;
"""


class Model:
    """Reference lifetime state, independent of the compiler."""

    def __init__(self) -> None:
        self.alive: dict[int, bool] = {}
        self.owners: dict[str, int] = {}      # place -> object, owns it
        self.aliases: dict[str, int] = {}     # place -> object, does not own
        self.weaks: dict[str, int] = {}       # place -> object, observes it
        self.destroyed = 0
        self.next_object = 0
        self.next_place = 0

    def fresh_place(self, prefix: str) -> str:
        self.next_place += 1
        return f"{prefix}{self.next_place}"

    def new_object(self) -> tuple[str, int]:
        self.next_object += 1
        identifier = self.next_object
        self.alive[identifier] = True
        place = self.fresh_place("owner")
        self.owners[place] = identifier
        return place, identifier

    def readable_places(self) -> list[str]:
        """Places naming a live object: owners and subscribers alike."""
        live = [p for p, o in self.owners.items() if self.alive[o]]
        live += [p for p, o in self.aliases.items() if self.alive[o]]
        return sorted(live)

    def object_of(self, place: str) -> int:
        if place in self.owners:
            return self.owners[place]
        return self.aliases[place]

    def add_alias(self, source: str) -> str:
        place = self.fresh_place("sub")
        self.aliases[place] = self.object_of(source)
        return place

    def add_weak(self, source: str) -> str:
        place = self.fresh_place("obs")
        self.weaks[place] = self.object_of(source)
        return place

    def owning_places(self) -> list[str]:
        return sorted(p for p, o in self.owners.items() if self.alive[o])

    def move_from(self, source: str) -> str:
        identifier = self.owners.pop(source)
        place = self.fresh_place("owner")
        self.owners[place] = identifier
        return place

    def delete(self, source: str) -> None:
        identifier = self.owners.pop(source)
        # The object dies once; every place naming it stops being usable.
        self.alive[identifier] = False
        self.destroyed += 1
        for place in [p for p, o in self.aliases.items() if o == identifier]:
            del self.aliases[place]

    def live_weaks(self) -> list[str]:
        return sorted(self.weaks)

    def weak_is_live(self, place: str) -> bool:
        return self.alive[self.weaks[place]]


def generate(seed: int, steps: int) -> tuple[str, int]:
    rng = random.Random(seed)
    model = Model()
    lines: list[str] = []

    def check_weaks(reason: str) -> None:
        for place in model.live_weaks():
            expected = "" if model.weak_is_live(place) else "!"
            lines.append(
                f"    assert({expected}{place}, "
                f'"{place} after {reason}");'
            )

    def check_count(reason: str) -> None:
        lines.append(
            f"    assert(destroyed == {model.destroyed}, "
            f'"destructor count after {reason}");'
        )

    for _ in range(steps):
        choices = ["new"]
        if model.readable_places():
            choices += ["alias", "weak", "read"]
        if model.owning_places():
            choices += ["move", "delete", "delete"]
        operation = rng.choice(choices)

        if operation == "new":
            place, identifier = model.new_object()
            lines.append(f"    Obj* {place} = new Obj(place, {identifier});")
            check_count(f"new {place}")
        elif operation == "alias":
            source = rng.choice(model.readable_places())
            place = model.add_alias(source)
            lines.append(f"    Obj* {place} = {source};")
        elif operation == "weak":
            source = rng.choice(model.readable_places())
            place = model.add_weak(source)
            lines.append(f"    weak Obj* {place} = {source};")
            check_weaks(f"observing {source}")
        elif operation == "read":
            source = rng.choice(model.readable_places())
            identifier = model.object_of(source)
            lines.append(
                f"    assert({source}.id == {identifier}, "
                f'"{source} reads its object");'
            )
        elif operation == "move":
            source = rng.choice(model.owning_places())
            place = model.move_from(source)
            lines.append(f"    Obj* {place} = move({source});")
            check_weaks(f"move out of {source}")
            check_count(f"move out of {source}")
        else:
            source = rng.choice(model.owning_places())
            model.delete(source)
            lines.append(f"    delete {source};")
            check_weaks(f"delete {source}")
            check_count(f"delete {source}")

    # Release whatever is still owned, so the program ends with no live object
    # and the total destructor count equals the number of objects created.
    for place in model.owning_places():
        model.delete(place)
        lines.append(f"    delete {place};")
        check_weaks(f"final release of {place}")
    check_count("the final release")

    lines.append(f'    assert(destroyed == {model.next_object}, '
                 f'"every object created ran its destructor exactly once");')
    lines.append('    println("ownership-model=ok");')
    lines.append("    return 0;")
    lines.append("}")

    return PRELUDE.format(seed=seed) + "\n".join(lines) + "\n", model.next_object


def run(command: list[str], timeout: float) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout,
        env=os.environ.copy(),
    )


def write_failure(work: Path, seed: int, source: str, reason: str,
                  result: subprocess.CompletedProcess[str] | None) -> None:
    work.mkdir(parents=True, exist_ok=True)
    reproducer = work / f"ownership-model-seed-{seed}.abs"
    reproducer.write_text(source, encoding="utf-8")
    report = [f"seed: {seed}", f"reason: {reason}"]
    if result is not None:
        report.append(f"exit: {result.returncode}")
        report.append("stdout:\n" + result.stdout)
        report.append("stderr:\n" + result.stderr)
    (work / f"ownership-model-seed-{seed}.log").write_text(
        "\n".join(report), encoding="utf-8")
    print(f"reproducer written to {reproducer}", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--compiler", required=True)
    parser.add_argument("--work-dir", required=True)
    parser.add_argument("--programs", type=int, default=20)
    parser.add_argument("--steps", type=int, default=24)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--timeout", type=float, default=120.0)
    args = parser.parse_args()

    work = Path(args.work_dir)
    work.mkdir(parents=True, exist_ok=True)
    executable = work / ("model-app.exe" if os.name == "nt" else "model-app")

    for index in range(args.programs):
        seed = args.seed + index
        source, objects = generate(seed, args.steps)
        program = work / f"ownership-model-{seed}.abs"
        program.write_text(source, encoding="utf-8")

        try:
            build = run([args.compiler, str(program), "--build-exe",
                         "-o", str(executable)], args.timeout)
        except subprocess.TimeoutExpired:
            write_failure(work, seed, source, "compiler timed out", None)
            return 1
        if build.returncode != 0:
            write_failure(work, seed, source, "compilation failed", build)
            return 1

        try:
            result = run([str(executable)], args.timeout)
        except subprocess.TimeoutExpired:
            write_failure(work, seed, source, "program timed out", None)
            return 1
        if result.returncode != 0 or "ownership-model=ok" not in result.stdout:
            write_failure(work, seed, source,
                          "runtime disagreed with the lifetime model", result)
            return 1
        lowered = (result.stdout + result.stderr).lower()
        for marker in ("leaked", "addresssanitizer", "use-after-free"):
            if marker in lowered:
                write_failure(work, seed, source, f"memory marker: {marker}",
                              result)
                return 1
        print(f"seed {seed}: {objects} objects, model agreed")

    print("ownership-model-generator=ok")
    return 0


if __name__ == "__main__":
    sys.exit(main())
